typography_spectrum: 0.36195798381231725
color:
  brandStrength: 0.08499778062105179
  lightness: 0.4955243666190654
  saturation: 0.1392968730069697
  rhythmicContrast: 0.3948791141156107
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
layout_spectrum: 0.21498763072304428
name: Electrica Bikes
navigation:
  - name: Electrica Bikes
    url: 'http://electricabikes.com'
    type: external
title: ELECTRICA
description: electric bikes
